[package]
name                  = "veryl-analyzer"
version               = "0.1.8"
authors.workspace     = true
repository.workspace  = true
keywords.workspace    = true
categories.workspace  = true
license.workspace     = true
readme.workspace      = true
description.workspace = true
edition               = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror     = {workspace = true}
veryl-parser  = {version = "0.1.8", path = "../parser"}
