[package]
name                  = "veryl-analyzer"
version               = "0.9.0"
authors.workspace     = true
repository.workspace  = true
keywords.workspace    = true
categories.workspace  = true
license.workspace     = true
readme.workspace      = true
description.workspace = true
edition               = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
Inflector       = "0.11.4"
itertools       = "0.12.1"
miette          = {workspace = true}
strnum_bitwidth = {workspace = true}
thiserror       = {workspace = true}
veryl-metadata  = {version = "0.9.0", path = "../metadata"}
veryl-parser    = {version = "0.9.0", path = "../parser"}
daggy           = "0.8.0"
bimap         = "0.6.3"

[dev-dependencies]
toml = {workspace = true}
