[package]
name                  = "veryl-analyzer"
version               = "0.5.1"
authors.workspace     = true
repository.workspace  = true
keywords.workspace    = true
categories.workspace  = true
license.workspace     = true
readme.workspace      = true
description.workspace = true
edition               = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
Inflector      = "0.11.4"
miette         = {workspace = true}
thiserror      = {workspace = true}
veryl-metadata = {version = "0.5.1", path = "../metadata"}
veryl-parser   = {version = "0.5.1", path = "../parser"}

[dev-dependencies]
toml = {workspace = true}
