[workspace]
members = [
    "crates/analyzer",
    "crates/emitter",
    "crates/formatter",
    "crates/languageserver",
    "crates/metadata",
    "crates/parser",
    "crates/tests",
    "crates/veryl",
]

[workspace.package]
authors     = ["dalance@gmail.com"]
repository  = "https://github.com/dalance/veryl"
keywords    = ["parser", "verilog", "systemverilog"]
categories  = ["parsing"]
license     = "MIT OR Apache-2.0"
readme      = "README.md"
description = "A modern hardware description language"

[workspace.dependencies]
serde     = {version = "1.0", features = ["derive"]}
thiserror = "1.0"

[workspace.metadata.release]
tag = false

[profile.dev.build-override]
opt-level = 3

[profile.release.build-override]
opt-level = 3

# Workaround for long time compilation
# https://github.com/rust-lang/rust/issues/106211
[profile.release]
codegen-units = 1
