[workspace]
members = [
    "crates/analyzer",
    "crates/emitter",
    "crates/formatter",
    "crates/languageserver",
    "crates/mdbook",
    "crates/metadata",
    "crates/parser",
    "crates/tests",
    "crates/veryl",
]
resolver = "2"

[workspace.package]
authors     = ["dalance@gmail.com"]
repository  = "https://github.com/veryl-lang/veryl"
keywords    = ["parser", "verilog", "systemverilog"]
categories  = ["parsing"]
license     = "MIT OR Apache-2.0"
readme      = "README.md"
description = "A modern hardware description language"

[workspace.dependencies]
anyhow          = "1.0"
clap            = {version = "4.5.6", features = ["derive"]}
futures         = "0.3.30"
log             = "0.4.20"
mdbook          = "0.4.40"
miette          = {version = "5.10", features = ["fancy"]}
once_cell       = "1.19"
regex           = "1.10.4"
semver          = {version = "1.0", features = ["serde"]}
serde           = {version = "1.0", features = ["derive"]}
serde_json      = "1.0"
similar         = {version = "2.5.0", features = ["text", "inline"]}
strnum_bitwidth = "0.1.2"
tempfile        = "3.10"
thiserror       = "1.0"
tokio           = {version = "1.38.0", features = ["full"]}
toml            = "0.7.8"
url             = {version = "2.5", features = ["serde"]}

[workspace.metadata.release]
tag = false

[profile.dev.build-override]
opt-level = 3

[profile.release.build-override]
opt-level = 3

[profile.release]
# Workaround for long time compilation
# https://github.com/rust-lang/rust/issues/106211
codegen-units = 1

[profile.bench]
debug = true
