[workspace]
members = [
    "crates/analyzer",
    "crates/emitter",
    "crates/formatter",
    "crates/languageserver",
    "crates/parser",
    "crates/tests",
    "crates/veryl",
]

[workspace.dependencies]
thiserror     = "1.0"

[profile.dev.build-override]
opt-level = 3

[profile.release.build-override]
opt-level = 3
