[workspace]
members = [
    "crates/analyzer",
    "crates/emitter",
    "crates/formatter",
    "crates/languageserver",
    "crates/parser",
    "crates/tests",
    "crates/veryl",
]

[workspace.package]
authors     = ["dalance@gmail.com"]
repository  = "https://github.com/dalance/veryl"
keywords    = ["parser", "verilog", "systemverilog"]
categories  = ["parsing"]
license     = "MIT OR Apache-2.0"
readme      = "../../README.md"
description = "A modern hardware description language"

[workspace.dependencies]
thiserror = "1.0"

[profile.dev.build-override]
opt-level = 3

[profile.release.build-override]
opt-level = 3
