[workspace]
members = [
    "crates/analyzer",
    "crates/emitter",
    "crates/formatter",
    "crates/languageserver",
    "crates/metadata",
    "crates/parser",
    "crates/tests",
    "crates/veryl",
]

[workspace.package]
authors     = ["dalance@gmail.com"]
repository  = "https://github.com/dalance/veryl"
keywords    = ["parser", "verilog", "systemverilog"]
categories  = ["parsing"]
license     = "MIT OR Apache-2.0"
readme      = "README.md"
description = "A modern hardware description language"

[workspace.dependencies]
serde     = {version = "1.0", features = ["derive"]}
thiserror = "1.0"

[workspace.metadata.release]
tag = false
pre-release-replacements = [
    {file="CHANGELOG.md", search="Unreleased", replace="v{{version}}"},
    {file="CHANGELOG.md", search="ReleaseDate", replace="{{date}}"},
    {file="CHANGELOG.md", search="Change Log", replace="Change Log\n\n## [Unreleased](https://github.com/dalance/veryl/compare/v{{version}}...Unreleased) - ReleaseDate"},
    {file="README.md", search = "changelog-v[0-9\\.]+", replace = "changelog-v{{version}}" },
]

[profile.dev.build-override]
opt-level = 3

[profile.release.build-override]
opt-level = 3
