[project]
name        = "veryl_testcase"
version     = "0.1.6"
authors     = ["dalance@gmail.com"]
description = "Testcases for test"
license     = "MIT"
repository  = "https://github.com/dalance/veryl"

[build]
clock_type    = "posedge"
reset_type    = "async_low"
filelist_type = "absolute"
target        = {type = "directory", path = "testcases/sv"}

[format]
indent_width = 4

[doc]
path = "target/veryl_doc"

[dependencies]
"https://github.com/dalance/veryl_sample" = [
    {version = "0.7.0", name = "veryl_sample1"},
    {version = "0.8.0", name = "veryl_sample2"},
]
