[project]
name    = "veryl_testcase"
version = "0.1.6"
license = "MIT"

[build]
clock_type    = "posedge"
reset_type    = "async_low"
filelist_type = "absolute"
target        = {type = "directory", path = "testcases/sv"}

[format]
indent_width = 4

[dependencies]
"https://github.com/dalance/veryl_sample" = [
    {version = "0.2.0", name = "veryl_sample1"},
    {version = "0.3.0", name = "veryl_sample2"},
]
