[project]
name = "veryl-testcase"
version = "0.1.0"

[build]
clock_type    = "posedge"
reset_type    = "async_low"
filelist_type = "absolute"
target        = {type = "directory", path = "testcases/sv"}

[format]
indent_width = 4
