[package]
name                  = "veryl-metadata"
version               = "0.6.0"
authors.workspace     = true
repository.workspace  = true
keywords.workspace    = true
categories.workspace  = true
license.workspace     = true
readme.workspace      = true
description.workspace = true
edition               = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
directories    = "5.0"
git-repository = {version = "0.35.0", optional = true, features = ["blocking-network-client", "blocking-http-transport-reqwest", "blocking-http-transport-reqwest-rust-tls"]}
log            = {workspace = true}
miette         = {workspace = true}
regex          = {workspace = true}
semver         = {workspace = true}
serde          = {workspace = true}
serde_regex    = "1.1"
spdx           = "0.10.3"
thiserror      = {workspace = true}
toml           = {workspace = true}
url            = {workspace = true}
uuid           = {version = "1.6", default-features = false, features = ["v5", "serde"]}
veryl-parser   = {version = "0.6.0", path = "../parser"}
walkdir        = "2.4.0"

[dev-dependencies]
tempfile       = {workspace = true}

[features]
default      = ["git-command"]
git-command  = []
git-gitoxide = ["dep:git-repository"]
