[package]
name                  = "veryl-metadata"
version               = "0.2.0"
authors.workspace     = true
repository.workspace  = true
keywords.workspace    = true
categories.workspace  = true
license.workspace     = true
readme.workspace      = true
description.workspace = true
edition               = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
miette       = {workspace = true}
semver       = {workspace = true}
serde        = {workspace = true}
thiserror    = {workspace = true}
toml         = "0.5.10"
veryl-parser = {version = "0.2.0", path = "../parser"}
