[package]
name                  = "veryl-metadata"
version               = "0.3.0"
authors.workspace     = true
repository.workspace  = true
keywords.workspace    = true
categories.workspace  = true
license.workspace     = true
readme.workspace      = true
description.workspace = true
edition               = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
directories    = "4.0"
git-repository = {version = "0.33.0", optional = true, features = ["blocking-network-client", "blocking-http-transport-reqwest", "blocking-http-transport-reqwest-rust-tls"]}
log            = {workspace = true}
miette         = {workspace = true}
regex          = {workspace = true}
semver         = {workspace = true}
serde          = {workspace = true}
spdx           = "0.10.0"
thiserror      = {workspace = true}
toml           = "0.7.0"
url            = {workspace = true}
veryl-parser   = {version = "0.3.0", path = "../parser"}
walkdir        = "2.3.2"

[features]
default      = ["git-command"]
git-command  = []
git-gitoxide = ["dep:git-repository"]
