[package]
name                  = "veryl-ls"
version               = "0.1.7"
authors.workspace     = true
repository.workspace  = true
keywords.workspace    = true
categories.workspace  = true
license.workspace     = true
readme.workspace      = true
description.workspace = true
edition               = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dashmap         = "5.4.0"
glob            = "0.3.0"
ropey           = "1.5.1"
serde_json      = "1.0"
tokio           = {version = "1.24.0", features = ["full"]}
tower-lsp       = "0.17.0"
veryl-analyzer  = {version = "0.1.7", path = "../analyzer"}
veryl-formatter = {version = "0.1.7", path = "../formatter"}
veryl-metadata  = {version = "0.1.7", path = "../metadata"}
veryl-parser    = {version = "0.1.7", path = "../parser"}
