[package]
name                  = "veryl"
version               = "0.7.1"
authors.workspace     = true
repository.workspace  = true
keywords.workspace    = true
categories.workspace  = true
license.workspace     = true
readme.workspace      = true
description.workspace = true
edition               = "2021"

[package.metadata.release]
tag = true
pre-release-replacements = [
    {file="../../CHANGELOG.md", search="Unreleased", replace="v{{version}}"},
    {file="../../CHANGELOG.md", search="ReleaseDate", replace="{{date}}"},
    {file="../../CHANGELOG.md", search="Change Log", replace="Change Log\n\n## [Unreleased](https://github.com/veryl-lang/veryl/compare/v{{version}}...Unreleased) - ReleaseDate"},
    {file="../../README.md", search = "changelog-v[0-9\\.]+", replace = "changelog-v{{version}}" },
    {file="../../support/vscode/package.json", search = "\"version\": \"[0-9\\.]+\",", replace = "\"version\": \"{{version}}\"," },
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap            = {workspace = true}
console         = "0.15.8"
fern            = "0.6.2"
handlebars      = "5.1"
log             = {workspace = true}
mdbook          = {workspace = true}
miette          = {workspace = true}
regex           = {workspace = true}
serde           = {workspace = true}
serde_json      = {workspace = true}
similar         = {version = "2.4.0", features = ["text", "inline"]}
tempfile        = {workspace = true}
thiserror       = {workspace = true}
veryl-analyzer  = {version = "0.7.1", path = "../analyzer"}
veryl-emitter   = {version = "0.7.1", path = "../emitter"}
veryl-formatter = {version = "0.7.1", path = "../formatter"}
veryl-metadata  = {version = "0.7.1", path = "../metadata"}
veryl-parser    = {version = "0.7.1", path = "../parser"}
