[package]
name                  = "veryl"
version               = "0.2.1"
authors.workspace     = true
repository.workspace  = true
keywords.workspace    = true
categories.workspace  = true
license.workspace     = true
readme.workspace      = true
description.workspace = true
edition               = "2021"

[package.metadata.release]
tag = true
pre-release-replacements = [
    {file="../../CHANGELOG.md", search="Unreleased", replace="v{{version}}"},
    {file="../../CHANGELOG.md", search="ReleaseDate", replace="{{date}}"},
    {file="../../CHANGELOG.md", search="Change Log", replace="Change Log\n\n## [Unreleased](https://github.com/dalance/veryl/compare/v{{version}}...Unreleased) - ReleaseDate"},
    {file="../../README.md", search = "changelog-v[0-9\\.]+", replace = "changelog-v{{version}}" },
    {file="../../support/vscode/package.json", search = "\"version\": \"[0-9\\.]+\",", replace = "\"version\": \"{{version}}\"," },
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap            = {workspace = true}
console         = "0.15.4"
directories     = "4.0"
env_logger      = "0.10.0"
git-repository  = {version = "0.33.0", features = ["blocking-network-client", "blocking-http-transport-reqwest", "blocking-http-transport-reqwest-rust-tls"]}
miette          = {workspace = true}
serde_json      = {workspace = true}
similar         = {version = "2.2.1", features = ["text", "inline"]}
thiserror       = {workspace = true}
veryl-analyzer  = {version = "0.2.1", path = "../analyzer"}
veryl-emitter   = {version = "0.2.1", path = "../emitter"}
veryl-formatter = {version = "0.2.1", path = "../formatter"}
veryl-metadata  = {version = "0.2.1", path = "../metadata"}
veryl-parser    = {version = "0.2.1", path = "../parser"}
walkdir         = "2.3.2"
