[package]
name = "veryl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap            = {version = "4.0.29", features = ["derive"]}
console         = "0.15.2"
env_logger      = "0.9.1"
miette          = "5.5.0"
parol_runtime   = {version = "0.9.0", features = ["auto_generation"]}
similar         = {version = "2.2.1", features = ["text", "inline"]}
veryl-parser    = {version = "0.1.0", path = "../parser"}
veryl-formatter = {version = "0.1.0", path = "../formatter"}
walkdir         = "2.3.2"
