[package]
name                  = "veryl"
version               = "0.1.0"
authors.workspace     = true
repository.workspace  = true
keywords.workspace    = true
categories.workspace  = true
license.workspace     = true
readme.workspace      = true
description.workspace = true
edition               = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap            = {version = "4.0.32", features = ["derive"]}
console         = "0.15.2"
env_logger      = "0.10.0"
similar         = {version = "2.2.1", features = ["text", "inline"]}
thiserror       = {workspace = true}
veryl-analyzer  = {version = "0.1.0", path = "../analyzer"}
veryl-emitter   = {version = "0.1.0", path = "../emitter"}
veryl-parser    = {version = "0.1.0", path = "../parser"}
veryl-formatter = {version = "0.1.0", path = "../formatter"}
walkdir         = "2.3.2"
