[package]
name                  = "veryl-emitter"
version               = "0.1.3"
authors.workspace     = true
repository.workspace  = true
keywords.workspace    = true
categories.workspace  = true
license.workspace     = true
readme.workspace      = true
description.workspace = true
edition               = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde          = {workspace = true}
veryl-metadata = {version = "0.1.3", path = "../metadata"}
veryl-parser   = {version = "0.1.3", path = "../parser"}
