[book]
authors = ["dalance"]
language = "en"
multilingual = false
src = "src"
title = "The Veryl Hardware Description Language"

[preprocessor.veryl]

[output.html]
curly-quotes = true

[output.html.fold]
enable = true
level  = 1

[output.playground]
command = "./playground.sh"
