[book]
authors = ["dalance"]
language = "en"
multilingual = false
src = "src"
title = "The Veryl Hardware Description Language"

[preprocessor.veryl]

[output.html]

[output.playground]
command = "./playground.sh"
