name: Deploy

on:
  push:
    branches:
      - master

jobs:
  playground:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: jetli/wasm-pack-action@v0.4.0
      - name: Build wasm
        run: wasm-pack build --target web -d playground/pkg --no-typescript
        working-directory: crates/wasm
      - name: Remove .gitignore
        run: rm playground/pkg/.gitignore
        working-directory: crates/wasm
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./crates/wasm/playground
          destination_dir: playground

  book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'
      - name: Build mdbook plugin
        run: cargo install --path crates/mdbook
      - name: Build mdbook
        run: mdbook build
        working-directory: book
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/book
          destination_dir: book
