name: Deploy

on:
  push:
    branches:
      - master

env:
  # Update the language picker in index.hbs to link new languages.
  LANGUAGES: ja

jobs:
  playground:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - uses: jetli/wasm-pack-action@v0.4.0
      - name: Build wasm
        run: wasm-pack build --target web -d playground/pkg --no-typescript
        working-directory: crates/wasm
      - name: Remove .gitignore
        run: rm playground/pkg/.gitignore
        working-directory: crates/wasm
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./crates/wasm/playground
          destination_dir: playground

  book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # We need the full history below.
          fetch-depth: 0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'
      - name: Install mdbook-i18n-helpers
        run: |
          cargo install mdbook-i18n-helpers --locked --version 0.3.0
      - name: Build mdbook plugin
        run: cargo install --path crates/mdbook
      - name: Build mdbook
        run: mdbook build
        working-directory: book
      - name: Build all translations
        working-directory: book
        run: |
          for po_lang in ${{ env.LANGUAGES }}; do
            POT_CREATION_DATE=$(grep --max-count 1 '^"POT-Creation-Date:' po/$po_lang.po | sed -E 's/".*: (.*)\\n"/\1/')
            if [[ $POT_CREATION_DATE == "" ]]; then
                POT_CREATION_DATE=now
            fi

            echo "::group::Building $po_lang translation as of $POT_CREATION_DATE"
            rm -r src/
            git restore --source "$(git rev-list -n 1 --before "$POT_CREATION_DATE" @)" src/

            # Set language and adjust site URL. Clear the redirects
            # since they are in sync with the source files, not the
            # translation.
            MDBOOK_BOOK__LANGUAGE=$po_lang \
            MDBOOK_OUTPUT__HTML__SITE_URL=/veryl/book/$po_lang/ \
            MDBOOK_OUTPUT__HTML__REDIRECT='{}' \
            mdbook build -d book/$po_lang
            mv book/$po_lang/html book/html/$po_lang
            echo "::endgroup::"
          done
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/book/html
          destination_dir: book
